os:
  - linux
  - osx
dist: trusty
sudo: required
language: bash
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mairix notmuch notmuch-mutt maildir-utils nmzmail; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mairix notmuch mu ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cpan install Mail::Box::Maildir && curl -O https://raw.githubusercontent.com/notmuch/notmuch/master/contrib/notmuch-mutt/notmuch-mutt && install notmuch-mutt /usr/local/bin/; fi
script:
  - ./t/t.sh
